
development:
  adapter: mysql
  encoding: utf8
  database: transect_development
  username: justin.shell
  password: dqDsLWcHEhwRZ
  socket: /tmp/mysql.sock

test:
  adapter: mysql
  database: 

production:
  adapter: mysql
  encoding: utf8
  database: transect
  username: justin.shell
  password: dqDsLWcHEhwRZ
  socket: /tmp/mysql.sock
