
development:
  adapter: mysql
  encoding: utf8
  database: transect_devel
  username: 
  password: dqDsLWcHEhwRZ
  host: 
  socket: /tmp/mysql.sock

test:
  adapter: mysql
  encoding: utf8
  database: transect_testing_db
  username:
  password:
  socket: /tmp/mysql.sock 

production:
  adapter: mysql
  encoding: utf8
  database: transect_production_db
  username: 
  password: 
  socket: /tmp/mysql.sock
