
development:
  adapter: mysql
  encoding: utf8
  database: development
  username: root
  password: 
  socket: /tmp/mysql.sock

test:
  adapter: sqlite3
  database: db/test.sqlite3
  timeout: 5000
  encoding: utf8

production:
  adapter: sqlite3
  database: db/production.sqlite3
  timeout: 5000
  encoding: utf8
